#!/usr/bin/env bash
# Install Nginx on a remote server, while setting it up with custom config
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx restart
