#!/usr/bin/env bash
# Install Nginx on a remote server, while setting it up with custom config
sudo su <<EOF
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw enable
echo "Hello World" > /var/www/html/index.nginx-debian.html
EOF
