#!/usr/bin/env bash
# Install Nginx on a remote server, while setting it up with custom config
apt-get update
apt-get -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
