#!/usr/bin/env bash
# Install Nginx on a remote server, while setting it up with custom config
apt-get update
apt-get -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error_404.html
echo -e "\tserver_name _;
\terror_page 404 /error_404.html;
\tlocation = /error_404.html {
\t\troot /usr/share/nginx/html;
\t\tinternal;
\t}
" > /tmp/new_config

sed -i '/server_name _;/{
    r /tmp/new_config
}' /etc/nginx/sites-available/default
rm /tmp/new_config
service nginx start
